CRM/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import LandingPageView, SignupView
from django.contrib.auth.views import LoginView,LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='home'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='leads/registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
]

leads/urls.py
from django.urls import path
from .views import lead_list, lead_detail, create_lead, update_lead, delete_lead, AssignAgentView

app_name = 'leads'

urlpatterns = [
    path('list/', lead_list, name='list'),
    path('create/', create_lead, name='create'),
    path('detail/<int:pk>/', lead_detail, name='detail'),
    path('update/<int:pk>/', update_lead, name='update'),
    path('delete/<int:pk>/', delete_lead, name='delete'),
    path('assign-agent/<int:pk>/', AssignAgentView.as_view(), name='assign_agent'),
]

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save


class User(AbstractUser):
    is_organisor = models.BooleanField(default=True)
    is_agent     = models.BooleanField(default=False)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Lead(models.Model):
    first_name   = models.CharField(max_length=100)
    last_name    = models.CharField(max_length=100)
    age          = models.IntegerField(default=0)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent        = models.ForeignKey("Agent", null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(post_user_created_signal, sender=User)

leads/forms.py
from django import forms
from .models import Lead, User, Agent
from django.contrib.auth.forms import UserCreationForm, UsernameField


class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name  = forms.CharField()
    age        = forms.IntegerField()



class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model         = User
        fields        = ('username',)
        field_classes = {'username': UsernameField}



class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=None)

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request')
        super().__init__(*args, **kwargs)
        # super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields['agent'].queryset = Agent.objects.filter(organisation=request.user.userprofile)

leads/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from .models import Lead, User, Agent
from .forms import LeadForm, CustomUserCreationForm, AssignAgentForm
from django.views.generic import TemplateView, CreateView, FormView
from agents.mixin import OrganisorAndLoginRequiredMixin
################################
def lead_list(request):
    if request.user.is_organisor:
        leads = Lead.objects.filter(organisation=request.user.userprofile, agent__isnull=False)
        unassigned_leads = Lead.objects.filter(organisation=request.user.userprofile, agent__isnull=True)
        # print(unassigned_leads.count())
        context = {'leads':leads, 'unassigned_leads':unassigned_leads}
    else:
        leads = Lead.objects.filter(organisation=request.user.agent.organisation, agent__isnull=False)
        context = {'leads':leads}

    return render(request, 'leads/lead_list.html', context)



class LandingPageView(TemplateView):
    template_name   = 'leads/home.html'

    
################################
def lead_detail(request, pk):
    lead = Lead.objects.filter(pk=pk)

    context = {'leads':lead}
    return render(request, 'leads/lead_details.html', context)


###############################
def create_lead(request):
    if request.user.is_organisor:
        if request.method == "POST":
            form = LeadForm(request.POST)
            if form.is_valid():
                first_name = form.cleaned_data['first_name']
                last_name = form.cleaned_data['last_name']
                age = form.cleaned_data['age']

                organisation = request.user.userprofile
                
                Lead.objects.create(first_name=first_name, last_name=last_name, age=age, organisation=organisation)
                return redirect('leads:list')
        else:
            form = LeadForm()

        context = {'form':form}
        return render(request, 'leads/create_lead.html', context)
    else:
        return redirect('leads:list')

##################################
def update_lead(request, pk):
    # lead = Lead.objects.get(pk=pk)
    lead = Lead.objects.filter(pk=pk)
    form = LeadForm()
    if request.method == "POST":
        form = LeadForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            age = form.cleaned_data['age']

            # lead.first_name = first_name
            # lead.last_name  = last_name
            # lead.age        = age
            # lead.save()

            lead = Lead.objects.filter(pk=pk).update(first_name=first_name,last_name=last_name,age=age)
            return redirect('leads:list')
    else:
        form = LeadForm()

    context = {'form':form}
    return render(request, 'leads/update_lead.html', context)


#####################################
def delete_lead(request,pk):
    lead = Lead.objects.filter(pk=pk)
    lead.delete()

    return redirect('leads:list')


#######################################
class SignupView(CreateView):
    template_name = 'leads/registration/signup.html'
    form_class    = CustomUserCreationForm

    def get_success_url(self):
        return reverse('login')

class AssignAgentView(OrganisorAndLoginRequiredMixin, FormView):
    template_name = 'leads/lead_assign.html'
    form_class    = AssignAgentForm
    
    def get_form_kwargs(self, **kwargs):
        kwargs = super().get_form_kwargs(**kwargs)
        kwargs.update({
            'request':self.request
        })
        return kwargs

    def form_valid(self, form):
        agent = form.cleaned_data['agent']
        lead  = Lead.objects.get(id=self.kwargs['pk'])
        print(lead, agent)
        lead.agent = agent
        lead.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('leads:list')

leads/templates/leads/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Leads</title>
</head>
<body>
        <a href="{% url 'home' %}"> < </a>
        <div style="float: right; padding-right:50px">
            {% if not user.is_authenticated %}
                <a href="{% url 'login' %}">login</a>
                <a href="{% url 'signup' %}">signup</a>
            {% endif %}
            
            {% if user.is_authenticated %}
                <a>Welcome {{user.username}}</a>
                <a href="{% url 'logout' %}" style="padding-left:20px">logout</a>
            {% endif %}

        </div>
        <hr>
        {% block main %}{% endblock main %}
</body>
</html>

leads/templates/leads/create_lead.html
{% extends 'leads/base.html' %}
{% block main %}

    <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit"> Submit</button>
    </form>
    
{% endblock main %}

leads/templates/leads/delete_lead.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Leads</title>
</head>
<body>
        <a href="{% url 'home' %}"> < </a>
        <hr>
        <h1>Are You Sure?</h1>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit"> Submit</button>
        </form>
</body>
</html>

leads/templates/leads/home.html
{% extends 'leads/base.html' %}

{% block main %}
    
    <h1>Home Page</h1>
    
    {% if not user.is_authenticated %}
        <p>Please sign in to view all the leads</p>
    {% endif %}

    {% if user.is_authenticated %}
        <a href="{% url 'leads:list' %}">View all the leads</a>
        <br>
            {% if request.user.is_organisor %}
                <a href="{% url 'agents:list' %}">View all the Agents</a>
            {% endif %}
    {% endif %}

{% endblock main %}

leads/templates/leads/lead.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
</head>
<body>
    
        <h1>All The Leads Below</h1>
        
        {% for lead in leads %}
           {{forloop.counter}}) <a href="/leads/detail/{{lead.id}} "> {{lead.first_name}} </a> <br>
            <a href="{% url 'leads:update' lead.id %}">Edit</a>
            <a href="{% url 'leads:delete' lead.id %}">Delete</a>
            <br><br>
        {% endfor %}

        <a href="/leads/create">Create New Leads</a>
        
</body>
</html>

leads/templates/leads/lead_assign.html
{% extends 'leads/base.html' %}

{% block main %}

        <h1>Assign to a Agent</h1>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Create">
        </form>

{% endblock main %}

leads/templates/leads/lead_details.html
{% extends 'leads/base.html' %}

{% block main %}

    {% for lead in leads %}
        <h1>Complete detail of {{lead.first_name}} {{lead.last_name}} </h1> <span> 
        <p>Age: {{lead.age}} </p>
        <p>Agent Email: {{lead.agent}} </p>
    {% endfor %}

{% endblock main %}

leads/templates/leads/lead_list.html
{% extends 'leads/base.html' %}

{% block main %}

    <h1>All The Leads Below</h1>
        <h3>Assign Leads</h3>

        {% for lead in leads %}
           {{forloop.counter}}) <a href="{% url 'leads:detail' lead.id %} "> {{lead.first_name}} </a> <br>
            <a href="{% url 'leads:update' lead.id %}">Edit</a>
            <a href="{% url 'leads:delete' lead.id %}">Delete</a>
            <br><br>
        {% endfor %}

        {% if unassigned_leads.exists %}
        
            <h3>Unassigned Leads</h3>

            {% for lead in unassigned_leads %}
            {{forloop.counter}}) <a href="{% url 'leads:detail' lead.id %} "> {{lead.first_name}} </a> <br>
                <a href="{% url 'leads:update' lead.id %}">Edit</a>
                <a href="{% url 'leads:delete' lead.id %}">Delete</a><br>
                (<a style="color:red;" href="{% url 'leads:assign_agent' lead.id %}">Assign an agent</a>)
                <br><br>
            {% endfor %}
        {% endif %}
        <a href="/leads/create">Create New Leads</a>


{% endblock main %}

leads/templates/leads/update_lead.html
{% extends 'leads/base.html' %}

{% block main %}

    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>    


{% endblock main %}