CRM/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import LandingPageView, SignupView
from django.contrib.auth.views import LoginView,LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='home'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='leads/registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
]

agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView

app_name = "agents"

urlpatterns = [
    path('list/', AgentListView.as_view(), name='list'),
    path('create/', AgentCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AgentDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AgentUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AgentDeleteView.as_view(), name='delete'),
]

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email','username','first_name','last_name')

agents/views.py
import random
from django.shortcuts import render, reverse
from django.views import generic
from leads.models import Agent
from .forms import AgentModelForm
from .mixin import OrganisorAndLoginRequiredMixin


# Create your views here.
class AgentListView(OrganisorAndLoginRequiredMixin, generic.ListView):
    # queryset            = Agent.objects.all()
    context_object_name = "agents"
    template_name       = 'agents/agent_list.html'

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)


class AgentCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    form_class    = AgentModelForm
    template_name = 'agents/agent_create.html'

    def get_success_url(self):
        return reverse('agents:list')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.set_password(f"{random.randint(0,10000)}")
        user.is_agent = True
        user.is_organisor = False
        user.save()
        Agent.objects.create(user=user, organisation=self.request.user.userprofile)

        return super(AgentCreateView, self).form_valid(form)


class AgentDetailView(OrganisorAndLoginRequiredMixin, generic.DetailView):
    queryset            = Agent.objects.all()
    context_object_name = "agent"
    template_name       = 'agents/agent_detail.html'


class AgentUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    form_class    = AgentModelForm
    queryset      = Agent.objects.all()
    template_name = 'agents/agent_update.html'

    def get_success_url(self):
        return reverse('agents:list')


class AgentDeleteView(OrganisorAndLoginRequiredMixin, generic.DeleteView):
    queryset      = Agent.objects.all()
    template_name = 'agents/agent_delete.html'

    def get_success_url(self):
        return reverse('agents:list')

agents/templates/agents/agent_create.html
{% extends 'leads/base.html' %}

{% block main %}

        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Create">
        </form>

{% endblock main %}

agents/templates/agents/agent_delete.html
{% extends 'leads/base.html' %}

{% block main %}

        <h1>Are You sure ?</h1>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Delete">
        </form>

{% endblock main %}

agents/templates/agents/agent_detail.html
{% extends 'leads/base.html' %}

{% block main %}

    <h1>Complete detail of {{agent.user}} {{agent.last_name}} </h1> <span> 

    <p>Organisation he works for: {{agent.organisation}} </p>

{% endblock main %}

agents/templates/agents/agent_list.html
{% extends 'leads/base.html' %}

{% block main %}

    {% for agent in agents %}
           {{forloop.counter}}) <a href="{% url 'agents:detail' agent.id %}"> {{agent.user}} </a> <br>
            <a href="{% url 'agents:update' agent.id %}">Edit</a>
            <a href="{% url 'agents:delete' agent.id %}">Delete</a>
            <br><br>
        {% endfor %}

        <a href="{% url 'agents:create' %}">Create New Agent</a>

{% endblock main %}

agents/templates/agents/agent_update.html
{% extends 'leads/base.html' %}

{% block main %}

        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Update">
        </form>

{% endblock main %}